### ISSUE TITLE
supporting openjfx

### ISSUE THREAD

**Issue by zcaudate** [halgari/fn-fx#35]
Openjfx is a months out and there are some significant changes:

- Builders have been deprecated since JFX8 and are completely removed in OpenFX
- There's a module system for JDK10+ that need some workarounds

are there plans for supporting openjfx?

**Comment by zcaudate** [comment]
@pmonks: ah that's fantastic.

**Comment by pmonks** [comment]
@halgari - any thoughts on the idea of creating a GitHub organisation for fn-fx, and moving development there?  That'll make it easier to "crowdsource" the ongoing development and maintenance of the library.

**Comment by pmonks** [comment]
@roti I see that you're also working actively on fn-fx.  Would you be interested in joining forces with @zcaudate and I in a new org-level fn-fx repository, if @halgari were ok with that path forward?

**Comment by zcaudate** [comment]
@pmonks + @halgari, a few comments:

- I would like to see more support for bindings, in conjunction with the virtual dom.
- some parts of the source code is a little bit hard to [understand](https://github.com/halgari/fn-fx/blob/master/src/fn_fx/controls.clj) and could be better structured.
- a roadmap would be nice.

**Comment by pmonks** [comment]
@halgari awesome!  It may be better to transfer the repository as it stands over to the new org, since that will also bring over issues, any wiki pages, etc.  If I set you up as an admin in the org (something I'll do regardless), would you be open to doing a transfer rather than a fork?

**Comment by halgari** [comment]
Sounds great, get it setup, and I'll do the transfer.

**Comment by pmonks** [comment]
Invitations sent!  cc @zcaudate, @roti

**Comment by roti** [comment]
@pmonks yes, I would be interested.
