### ISSUE TITLE
Unable to open DISPLAY

### ISSUE THREAD

**Issue by crinklywrappr** [halgari/fn-fx#96]
I'm looking for a way to easily render images & text directly to the linux framebuffer, with hardware acceleration if supported.  It looks like javafx fits the bill, based on what I've read eg https://unix.stackexchange.com/questions/272786/how-does-javafx-takes-control-of-the-raspberry-pi.

So, I'm sitting at a VT, trying to run the hello world program and it looks like it expects an X server to be running.  What's the deal?

**Comment by pmonks** [comment]
This is more of a JavaFX question than an fn-fx question, but as far as I know, yes JavaFX does indeed require an X server in Linux environments, though that server could be a virtual framebuffer (e.g. [Xvfb](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml)).

**Comment by crinklywrappr** [comment]
That's true, I was hoping there was a way to target the framebuffer using this library.
